== Cálculo II (José Edilson Filho)
:stem: asciimath

Entrega de provas corrigidas e média da turma (3,85).

Pra quem estava: 4 questões de máximo e 4 de mínimo para a próxima aula, valendo 1 ponto extra. Sugestão de página: 885, 18 questões.

Data da próxima prova: 18/06/2026 (quinta-feira). Conteúdo:

 - Máximo e mínimo.

 - Multiplicador de Lagrange.

 - Uma questão de ponto crítico.

Para classificar ponto crítico: stem:[D_p = f_(\x\x) * f_(yy) - (f_(xy))^2].

 - stem:[f_(\x\x) < 0] ou stem:[f_(\x\x) <= 0]: sela

 - stem:[f_(\x\x) > 0] e stem:[D_p > 0]: mínimo.

 - stem:[f_(\x\x) > 0] e stem:[D_p < 0]: máximo.

Exemplo: pontos críticos de stem:[f(x,y,z) = x^2 + (y-7)^2 + (z+10)^2]

[stem]
++++
f_x = 0 = 2*x
f_y = 0 = 2*(y-7)^1*1
f_z = 0 = 2*(z+10)

2*x = 0 -> x = 0
2*(y-7) = 0 -> 2*y - 14 = 0
2*(z+10) = 0 -> z = -10
++++

Ponto crítico é stem:[(0, 7, -10)]

Exemplo: Ponto crítico de stem:[f(x, y) = x*y + 1/x + 1/y].

[stem]
++++
f_x = 0 = y - 1/(x^2)
f_y = 0 = x - 1/(y^2)

y = i/(x^2) -> y^2 = 1/(x^4) -> x^4 = 1/(y^2)
x = 1/(y^2)
++++

[stem]
++++
P = (1, 1)
++++

Exemplo: Ponto crítico de stem:[f(x, y) = x*sen(y)].

[stem]
++++
f_x = 0 = sen(y)
f_y = 0 = x*cos(y)

sen(y) = 0 -> y = k*pi ; k in ZZ
x*cos(y) = 0
++++

Se stem:[k=2*n; n in ZZ], então stem:[y=2*n*pi]. Logo, stem:[cos(y)]

Dois pontos críticos: stem:[(0, 2*n)] e stem:[(0, 2*n+1)].

== Laboratório de sistemas operacionais (Flávia)

Continuação do estudo de processos em C.

Atividade será disponibilizada usando como base o mini shell que foi feito.
