== Cálculo (José Edilson)
:stem:

Multiplicador de Lagrange com duas restrições.

Exemplo:ste:[f(x,y,z) = x+2*y+3*z], encontre o valor de máximo na curva de interseção do plano stem:[x-y+z=1] com o cilindro stem:[x^2+y^2=1].

[stem]
++++
g(x,y,z) = x-y+z = 1

h(x,y,z) = x^2+y^2 = 1

grad(f) = lambda*grad(g) + mu*grad(h)

grad(f) = (1,2,3)

grad(g) = (1,-1,1)

grad(h) = (2*x, 2*y, 0)

(1, 2, 3) = lambda*(1, -1, 1) + mu*(2*x, 2*y, 0)

x = -1/mu

y = 5/(2*mu)

lambda = 3

x^2 + y^2 = 1 -> 1/(mu^2) + 25/(4*mu^2) = 1 -> mu  = +- sqrt(25)/5

"..."

P_1 = (-2/sqrt(25), 5/sqrt(25),  (sqrt(25)+7)/sqrt(25));
P_2 = (2/sqrt(25), -5/sqrt(25),  (sqrt(25)+7)/sqrt(25))
++++

À completar: como chegou em stem:[lambda=3]?

Observação: para 3 dimensões, são necessárias 5 equações.

**Exemplo:** stem:[f(x,y) = 2*x^2 + 3*y^2 - 4*x - 5] com restrição stem:[x^2 + y^2 = 16], encontre os vetores extremos.

[stem]
++++
g(x,y) = x^2+y^2 = 16

grad(g) = (2*x, 2*y)

grad(f) = (4*x-4, 64) = lambda*grad(g) = lambda*(2*x, 2*y)

4*x-4 = lambda*2*x

6*y = lambda*2*y

x^2 + y^2 = 16

"..."

P_1 = (-2, sqrt(12)); P_2 = (-2, -sqrt(12))
++++

**Exemplos:** stem:[f(x,y) = e^(-x*y)] com restrição stem:[x^2+4*y^2=1], econtre os vetores extremos.

[stem]
++++
-y*e^(-x*y) = 2*lambda*x

-x*e^(-x*y) = 2*lambda*y

x^2+y^2 = 1

x != 0; y != 0
++++

TODO: isolar stem:[e^(-x*y)]

== Sistemas operacionais (Regiane Kawasaki)

**Assuntos:**

 - Métodos de alocação de memória: contínua, paginada e segmentada.

 - Memória virtual e real, páginas, frames.

Adições de temas à tarefa de pesquisa, vide log [2026-06-09](2026-06-09.adoc):

 - Sistemas operacionais podem trocar entre modelo paginado e segmentado? Podem usar ambos ao mesmo tempo? Como?

 - Qual é o tamanho das páginas de memória agora? E no passado?
